// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gctvmwuwycvquypvhnxo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdjdHZtd3V3eWN2cXV5cHZobnhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyMjA4NTgsImV4cCI6MjA2MDc5Njg1OH0.NCoudRPWjfv02SVeoc0LpIjgADcMVcSGr2mTfzsAU38";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);